[package]
name = "day5"
version = "0.1.0"
authors = ["Joachim Burket <joachim.burket@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
